hx711-pico-c: include/hx711_multi_reader.pio.h File Reference
hx711_multi_reader.pio.h File Reference
#include "hardware/pio.h"
#include <assert.h>
#include <stddef.h>
#include "hardware/clocks.h"
#include "hardware/pio_instructions.h"
#include "hardware/structs/clocks.h"
#include "hx711_multi.h"
#include "util.h"
Macros
#define hx711_multi_reader_wrap_target 3
#define hx711_multi_reader_wrap 18
#define hx711_multi_reader_HZ 10000000
#define hx711_multi_reader_offset_bitloop_in_pins_bit_count 9u
Functions
static pio_sm_config hx711_multi_reader_program_get_default_config (uint offset)
void hx711_multi_pio_init (hx711_multi_t *const hxm)
void hx711_multi_reader_program_init (hx711_multi_t *const hxm)
Variables
static const uint16_t hx711_multi_reader_program_instructions []
static const struct pio_program hx711_multi_reader_program
Macro Definition Documentation
hx711_multi_reader_HZ
#define hx711_multi_reader_HZ 10000000
Definition at line 18 of file hx711_multi_reader.pio.h.
hx711_multi_reader_offset_bitloop_in_pins_bit_count
#define hx711_multi_reader_offset_bitloop_in_pins_bit_count 9u
Definition at line 20 of file hx711_multi_reader.pio.h.
hx711_multi_reader_wrap
#define hx711_multi_reader_wrap 18
Definition at line 16 of file hx711_multi_reader.pio.h.
hx711_multi_reader_wrap_target
#define hx711_multi_reader_wrap_target 3
Definition at line 15 of file hx711_multi_reader.pio.h.
Function Documentation
hx711_multi_pio_init()
void hx711_multi_pio_init (hx711_multi_t *const hxm)
Definition at line 89 of file hx711_multi_reader.pio.h.
{
     assert(hxm != NULL);
     assert(hxm->_pio != NULL);
     assert(hxm->_chips_len > 0);
     pio_gpio_init(
         hxm->_pio,
         hxm->_clock_pin);
     util_pio_gpio_contiguous_init(
         hxm->_pio,
         hxm->_data_pin_base,
         hxm->_chips_len);
     // make sure conversion done is valid and routable
     assert(util_routable_pio_interrupt_num_is_valid(
         HX711_MULTI_CONVERSION_DONE_IRQ_NUM));
     pio_interrupt_clear(
         hxm->_pio,
         HX711_MULTI_CONVERSION_DONE_IRQ_NUM);
     // make sure data ready is valid and not routable
     // although this is not strictly necessary
     assert(util_pio_interrupt_num_is_valid(
         HX711_MULTI_DATA_READY_IRQ_NUM));
     assert(!util_routable_pio_interrupt_num_is_valid(
         HX711_MULTI_DATA_READY_IRQ_NUM));
     pio_interrupt_clear(
         hxm->_pio,
         HX711_MULTI_DATA_READY_IRQ_NUM);
 }
References hx711_multi_t::_chips_len, hx711_multi_t::_clock_pin, hx711_multi_t::_data_pin_base, hx711_multi_t::_pio, HX711_MULTI_CONVERSION_DONE_IRQ_NUM, HX711_MULTI_DATA_READY_IRQ_NUM, util_pio_gpio_contiguous_init(), util_pio_interrupt_num_is_valid(), and util_routable_pio_interrupt_num_is_valid().
hx711_multi_reader_program_get_default_config()
static pio_sm_config hx711_multi_reader_program_get_default_config (uint offset) inline static
Definition at line 53 of file hx711_multi_reader.pio.h.
{
     pio_sm_config c = pio_get_default_sm_config();
     sm_config_set_wrap(&c, offset + hx711_multi_reader_wrap_target, offset + hx711_multi_reader_wrap);
     sm_config_set_sideset(&c, 2, true, false);
     return c;
 }
References hx711_multi_reader_wrap, and hx711_multi_reader_wrap_target.
Referenced by hx711_multi_reader_program_init().
hx711_multi_reader_program_init()
void hx711_multi_reader_program_init (hx711_multi_t *const hxm)
Definition at line 116 of file hx711_multi_reader.pio.h.
{
     assert(hxm != NULL);
     assert(hxm->_pio != NULL);
     hxm->_pio->instr_mem[hxm->_reader_offset + hx711_multi_reader_offset_bitloop_in_pins_bit_count] =
         pio_encode_in(pio_pins, hxm->_chips_len);
     pio_sm_config cfg = hx711_multi_reader_program_get_default_config(
         hxm->_reader_offset);
     const float div = (float)(clock_get_hz(clk_sys)) / (uint)hx711_multi_reader_HZ;
     sm_config_set_clkdiv(
         &cfg,
         div);
     //clock pin setup
     pio_sm_set_out_pins(
         hxm->_pio,
         hxm->_reader_sm,
         hxm->_clock_pin,
         1);
     pio_sm_set_set_pins(
         hxm->_pio,
         hxm->_reader_sm,
         hxm->_clock_pin,
         1);
     pio_sm_set_consecutive_pindirs(
         hxm->_pio,
         hxm->_reader_sm,
         hxm->_clock_pin,
         1,
         true);
     sm_config_set_set_pins(
         &cfg,
         hxm->_clock_pin,
         1);
     sm_config_set_out_pins(
         &cfg,
         hxm->_clock_pin,
         1);
     sm_config_set_sideset_pins(
         &cfg,
         hxm->_clock_pin);
     //data pins
     pio_sm_set_in_pins(
         hxm->_pio,
         hxm->_reader_sm,
         hxm->_data_pin_base);
     pio_sm_set_consecutive_pindirs(
         hxm->_pio,
         hxm->_reader_sm,
         hxm->_data_pin_base,
         hxm->_chips_len,
         false);                 //false = input
     sm_config_set_in_pins(
         &cfg,
         hxm->_data_pin_base);
     sm_config_set_in_shift(
         &cfg,
         false,                  //false = shift in left
         false,                  //false = autopush disabled
         hxm->_chips_len);
     pio_sm_clear_fifos(
         hxm->_pio,
         hxm->_reader_sm);
     hxm->_reader_default_config = cfg;
 }
References hx711_multi_t::_chips_len, hx711_multi_t::_clock_pin, hx711_multi_t::_data_pin_base, hx711_multi_t::_pio, hx711_multi_t::_reader_default_config, hx711_multi_t::_reader_offset, hx711_multi_t::_reader_sm, hx711_multi_reader_HZ, hx711_multi_reader_offset_bitloop_in_pins_bit_count, and hx711_multi_reader_program_get_default_config().
Variable Documentation
hx711_multi_reader_program
const struct pio_program hx711_multi_reader_program static
Initial value:
= {
    .instructions = hx711_multi_reader_program_instructions,
    .length = 19,
    .origin = -1,
}
Definition at line 22 of file hx711_multi_reader.pio.h.
hx711_multi_reader_program_instructions
const uint16_t hx711_multi_reader_program_instructions[] static
Initial value:
= {
    0xe020,
    0x8080,
    0x6020,
    0xe057,
    0x4060,
    0x8000,
    0x20c4,
    0xc040,
    0xe001,
    0x4001,
    0x8000,
    0x1088,
    0xc000,
    0x9880,
    0x6020,
    0x1023,
    0xa041,
    0xe101,
    0x1191,
}
Definition at line 22 of file hx711_multi_reader.pio.h.