hx711-pico-c: include/util.h File Reference
util.h File Reference
#include <stdint.h>
#include "hardware/pio.h"
#include "hardware/platform_defs.h"
#include "hardware/sync.h"
#include "pico/mutex.h"
#include "pico/types.h"
Macros
#define UTIL_NUM_DMA_IRQS UINT8_C(2)
#define UTIL_DMA_IRQ_INDEX_MIN UINT8_C(0)
#define UTIL_DMA_IRQ_INDEX_MAX UINT8_C(UTIL_NUM_DMA_IRQS - 1)
#define UTIL_PIO_IRQ_INDEX_MIN UINT8_C(0)
#define UTIL_PIO_IRQ_INDEX_MAX UINT8_C(NUM_PIOS - 1)
#define UTIL_PIO_INTERRUPT_NUM_MIN UINT8_C(0)
#define UTIL_PIO_INTERRUPT_NUM_MAX UINT8_C(7)
#define UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MIN UINT8_C(0)
#define UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MAX UINT8_C(3)
#define UTIL_MUTEX_BLOCK(mut, ...)
#define UTIL_INTERRUPTS_OFF_BLOCK(...)
#define UTIL_DECL_IN_RANGE_FUNC(TYPE)
Functions
bool util_dma_irq_index_is_valid (const uint idx)
Check whether a DMA IRQ index is valid.
uint util_dma_get_irq_from_index (const uint idx)
Gets the NVIC DMA IRQ number using the DMA IRQ index.
int util_dma_get_index_from_irq (const uint irq_num)
Gets the DMA IRQ index using the NVIC IRQ number.
void util_dma_set_exclusive_channel_irq_handler (const uint irq_index, const uint channel, const irq_handler_t handler, const bool enabled)
Set and enable an exclusive handler for a DMA channel.
uint32_t util_dma_get_transfer_count (const uint channel)
Get the transfer count for a given DMA channel. When a DMA transfer is active, this count is the number of transfers remaining.
bool util_dma_channel_wait_for_finish_timeout (const uint channel, const absolute_time_t *const end)
Wait until channel has completed transferring up to a timeout.
uint util_dma_get_irqn (const uint irq_index)
Gets the NVIC IRQ number based on the DMA IRQ index.
void util_dma_channel_set_quiet (const uint channel, const bool quiet)
Sets a DMA channel's IRQ quiet mode.
void util_gpio_set_contiguous_input_pins (const uint base, const uint len)
Sets GPIO pins from base to base + len to input.
void util_gpio_set_output (const uint gpio)
Initialises and sets GPIO pin to output.
void util_irq_set_exclusive_pio_interrupt_num_handler (PIO const pio, const uint irq_index, const uint pio_interrupt_num, const irq_handler_t handler, const bool enabled)
Set and enable an exclusive interrupt handler for a given pio_interrupt_num.
bool util_pio_irq_index_is_valid (const uint idx)
Check whether PIO IRQ index is valid.
uint util_pio_get_irq_from_index (PIO const pio, const uint idx)
Gets the NVIC PIO IRQ number using a PIO pointer and PIO IRQ index.
int util_pio_get_index_from_irq (const uint irq_num)
Gets the PIO IRQ index using the NVIC IRQ number.
PIO const util_pio_get_pio_from_irq (const uint irq_num)
Gets the PIO using the NVIC IRQ number.
uint util_pion_get_irqn (PIO const pio, const uint irq_index)
uint util_pio_get_pis_from_pio_interrupt_num (const uint pio_interrupt_num)
void util_pio_gpio_contiguous_init (PIO const pio, const uint base, const uint len)
Inits GPIO pins for PIO from base to base + len.
void util_pio_sm_clear_rx_fifo (PIO const pio, const uint sm)
Clears a given state machine's RX FIFO.
void util_pio_sm_clear_osr (PIO const pio, const uint sm)
Clears a given state machine's OSR.
void util_pio_sm_clear_isr (PIO const pio, const uint sm)
Clears a given state machine's ISR.
bool util_pio_sm_is_enabled (PIO const pio, const uint sm)
Check whether a given state machine is enabled.
bool util_pio_interrupt_num_is_valid (const uint pio_interrupt_num)
Check whether a PIO interrupt number is valid.
bool util_routable_pio_interrupt_num_is_valid (const uint pio_interrupt_num)
Check whether a PIO interrupt number is a valid routable interrupt number.
void util_pio_interrupt_wait (PIO const pio, const uint pio_interrupt_num)
Waits for a given PIO interrupt to be set.
void util_pio_interrupt_wait_cleared (PIO const pio, const uint pio_interrupt_num)
Waits until a given PIO interrupt is cleared.
bool util_pio_interrupt_wait_cleared_timeout (PIO const pio, const uint pio_interrupt_num, const absolute_time_t *const end)
Waits until the given interrupt is cleared, up to a maximum timeout.
void util_pio_interrupt_wait_clear (PIO const pio, const uint pio_interrupt_num)
Waits for a given PIO interrupt to be set and then clears it.
bool util_pio_interrupt_wait_timeout (PIO const pio, const uint pio_interrupt_num, const absolute_time_t *const end)
Waits for a given PIO to be set within the timeout period.
bool util_pio_interrupt_wait_clear_timeout (PIO const pio, const uint pio_interrupt_num, const absolute_time_t *const end)
Waits for a given PIO to be set within the timeout period and then clears it.
bool util_pio_sm_try_get (PIO const pio, const uint sm, uint32_t *const word, const uint threshold)
Attempts to get a word from the state machine's RX FIFO if more than threshold words are in the buffer.
Variables
const uint8_t util_pio_to_irq_map [NUM_PIOS *2]
Quick lookup for finding an NVIC IRQ number for a PIO and interrupt index number.
const uint8_t util_dma_to_irq_map [UTIL_NUM_DMA_IRQS]
Quick lookup for finding an NVIC IRQ number for a DMA interrupt index number.
Macro Definition Documentation
UTIL_DECL_IN_RANGE_FUNC
#define UTIL_DECL_IN_RANGE_FUNC (TYPE)
Value:
    bool util_ ## TYPE ##_in_range( \
        const TYPE val, \
        const TYPE min, \
        const TYPE max);
Definition at line 82 of file util.h.
UTIL_DMA_IRQ_INDEX_MAX
#define UTIL_DMA_IRQ_INDEX_MAX UINT8_C(UTIL_NUM_DMA_IRQS - 1)
Definition at line 41 of file util.h.
UTIL_DMA_IRQ_INDEX_MIN
#define UTIL_DMA_IRQ_INDEX_MIN UINT8_C(0)
Definition at line 40 of file util.h.
UTIL_INTERRUPTS_OFF_BLOCK
#define UTIL_INTERRUPTS_OFF_BLOCK (...)
Value:
    do { \
        const uint32_t interrupt_status_cb918069_eadf_49bc_9d8c_a8a4defad20c = save_and_disable_interrupts(); \
        __VA_ARGS__ \
        restore_interrupts(interrupt_status_cb918069_eadf_49bc_9d8c_a8a4defad20c); \
    } while(0)
Definition at line 75 of file util.h.
UTIL_MUTEX_BLOCK
#define UTIL_MUTEX_BLOCK (mut, ...)
Value:
    do { \
        mutex_enter_blocking(&mut); \
        __VA_ARGS__ \
        mutex_exit(&mut); \
    } while(0)
Definition at line 59 of file util.h.
UTIL_NUM_DMA_IRQS
#define UTIL_NUM_DMA_IRQS UINT8_C(2)
Definition at line 38 of file util.h.
UTIL_PIO_INTERRUPT_NUM_MAX
#define UTIL_PIO_INTERRUPT_NUM_MAX UINT8_C(7)
Definition at line 47 of file util.h.
UTIL_PIO_INTERRUPT_NUM_MIN
#define UTIL_PIO_INTERRUPT_NUM_MIN UINT8_C(0)
Definition at line 46 of file util.h.
UTIL_PIO_IRQ_INDEX_MAX
#define UTIL_PIO_IRQ_INDEX_MAX UINT8_C(NUM_PIOS - 1)
Definition at line 44 of file util.h.
UTIL_PIO_IRQ_INDEX_MIN
#define UTIL_PIO_IRQ_INDEX_MIN UINT8_C(0)
Definition at line 43 of file util.h.
UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MAX
#define UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MAX UINT8_C(3)
Definition at line 50 of file util.h.
UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MIN
#define UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MIN UINT8_C(0)
Definition at line 49 of file util.h.
Function Documentation
util_dma_channel_set_quiet()
void util_dma_channel_set_quiet (const uint channel, const bool quiet)
Sets a DMA channel's IRQ quiet mode.
Parameters
channel
quiet true for quiet otherwise false
Definition at line 161 of file util.c.
                       {
         check_dma_channel_param(channel);
         dma_channel_config cfg = dma_get_channel_config(channel);
         channel_config_set_irq_quiet(&cfg, quiet);
         dma_channel_set_config(channel, &cfg, false);
 }
Referenced by hx711_multi_close().
util_dma_channel_wait_for_finish_timeout()
bool util_dma_channel_wait_for_finish_timeout (const uint channel, const absolute_time_t *const end)
Wait until channel has completed transferring up to a timeout.
Parameters
channel
end
Returns
true if transfer completed
false is timeout was reached
Definition at line 126 of file util.c.
{
         check_dma_channel_param(channel);
         assert(end != NULL);
         assert(!is_nil_time(*end));
         while(!time_reached(*end)) {
             if(!dma_channel_is_busy(channel)) {
                 return true;
             }
         }
         return false;
 }
util_dma_get_index_from_irq()
int util_dma_get_index_from_irq (const uint irq_num)
Gets the DMA IRQ index using the NVIC IRQ number.
Parameters
irq_num
Returns
int -1 is returned for no match.
Definition at line 78 of file util.c.
{
     check_irq_param(irq_num);
     assert(util_dma_to_irq_map != NULL);
     switch(irq_num) {
         case DMA_IRQ_0:
             return 0;
         case DMA_IRQ_1:
             return 1;
         default:
             return -1;
     }
 }
References util_dma_to_irq_map.
util_dma_get_irq_from_index()
uint util_dma_get_irq_from_index (const uint idx)
Gets the NVIC DMA IRQ number using the DMA IRQ index.
Parameters
idx
Returns
uint
Definition at line 72 of file util.c.
{
     assert(util_dma_irq_index_is_valid(idx));
     assert(util_dma_to_irq_map != NULL);
     return util_dma_to_irq_map[idx];
 }
References util_dma_irq_index_is_valid(), and util_dma_to_irq_map.
util_dma_get_irqn()
uint util_dma_get_irqn (const uint irq_index)
Gets the NVIC IRQ number based on the DMA IRQ index.
Parameters
irq_index 0 or 1
Returns
uint DMA_IRQ_0 or DMA_IRQ_1
Definition at line 144 of file util.c.
{
     assert(util_dma_to_irq_map != NULL);
     assert(util_uint_in_range(
         irq_index,
         UTIL_DMA_IRQ_INDEX_MIN,
         UTIL_DMA_IRQ_INDEX_MAX));
     const uint irq_num = util_dma_to_irq_map[
         irq_index];
     check_irq_param(irq_num);
     return irq_num;
 }
References UTIL_DMA_IRQ_INDEX_MAX, UTIL_DMA_IRQ_INDEX_MIN, and util_dma_to_irq_map.
Referenced by hx711_multi__async_dma_irq_handler(), hx711_multi__init_irq(), hx711_multi__is_initd(), hx711_multi_close(), and util_dma_set_exclusive_channel_irq_handler().
util_dma_get_transfer_count()
uint32_t util_dma_get_transfer_count (const uint channel)
Get the transfer count for a given DMA channel. When a DMA transfer is active, this count is the number of transfers remaining.
Parameters
channel
Returns
uint32_t
Definition at line 121 of file util.c.
{
     check_dma_channel_param(channel);
     return (uint32_t)dma_hw->ch[channel].transfer_count;
 }
util_dma_irq_index_is_valid()
bool util_dma_irq_index_is_valid (const uint idx)
Check whether a DMA IRQ index is valid.
Parameters
idx
Returns
true
false
Definition at line 65 of file util.c.
{
     return util_uint_in_range(
         idx,
         UTIL_DMA_IRQ_INDEX_MIN,
         UTIL_DMA_IRQ_INDEX_MAX);
 }
References UTIL_DMA_IRQ_INDEX_MAX, and UTIL_DMA_IRQ_INDEX_MIN.
Referenced by hx711_multi__init_asert(), util_dma_get_irq_from_index(), and util_dma_set_exclusive_channel_irq_handler().
util_dma_set_exclusive_channel_irq_handler()
void util_dma_set_exclusive_channel_irq_handler (const uint irq_index, const uint channel, const irq_handler_t handler, const bool enabled)
Set and enable an exclusive handler for a DMA channel.
Parameters
irq_index
channel
handler
enabled
Definition at line 94 of file util.c.
{
         assert(util_dma_irq_index_is_valid(irq_index));
         check_dma_channel_param(channel);
         assert(handler != NULL);
         const uint irq_num = util_dma_get_irqn(irq_index);
         dma_irqn_set_channel_enabled(
             irq_index,
             channel,
             enabled);
         irq_set_exclusive_handler(
             irq_num,
             handler);
         irq_set_enabled(
             irq_num,
             enabled);
 }
References util_dma_get_irqn(), and util_dma_irq_index_is_valid().
util_gpio_set_contiguous_input_pins()
void util_gpio_set_contiguous_input_pins (const uint base, const uint len)
Sets GPIO pins from base to base + len to input.
Parameters
base
len
Definition at line 170 of file util.c.
                     {
         assert(len > 0);
         const uint l = base + len - 1;
         for(uint i = base; i <= l; ++i) {
             check_gpio_param(i);
             gpio_set_input_enabled(i, true);
         }
 }
Referenced by hx711_multi_init().
util_gpio_set_output()
void util_gpio_set_output (const uint gpio)
Initialises and sets GPIO pin to output.
Parameters
gpio
Definition at line 185 of file util.c.
{
     check_gpio_param(gpio);
     gpio_init(gpio);
     gpio_set_dir(gpio, true);
 }
Referenced by hx711_init(), and hx711_multi_init().
util_irq_set_exclusive_pio_interrupt_num_handler()
void util_irq_set_exclusive_pio_interrupt_num_handler (PIO const pio, const uint irq_index, const uint pio_interrupt_num, const irq_handler_t handler, const bool enabled)
Set and enable an exclusive interrupt handler for a given pio_interrupt_num.
Parameters
pio
irq_index
pio_interrupt_num
handler
enabled
Definition at line 191 of file util.c.
{
         check_pio_param(pio);
         assert(util_pio_irq_index_is_valid(irq_index));
         assert(util_routable_pio_interrupt_num_is_valid(pio_interrupt_num));
         assert(handler != NULL);
         const uint irq_num = util_pio_get_irq_from_index(
             pio,
             irq_index);
         const uint pis = util_pio_get_pis_from_pio_interrupt_num(
             pio_interrupt_num);
         pio_set_irqn_source_enabled(
             pio,
             irq_index,
             pis,
             enabled);
         irq_set_exclusive_handler(
             irq_num,
             handler);
         irq_set_enabled(
             irq_num,
             enabled);
 }
References util_pio_get_irq_from_index(), util_pio_get_pis_from_pio_interrupt_num(), util_pio_irq_index_is_valid(), and util_routable_pio_interrupt_num_is_valid().
util_pio_get_index_from_irq()
int util_pio_get_index_from_irq (const uint irq_num)
Gets the PIO IRQ index using the NVIC IRQ number.
Parameters
irq_num
Returns
int -1 is returned for no match.
Definition at line 267 of file util.c.
{
     check_irq_param(irq_num);
     switch(irq_num) {
         case PIO0_IRQ_0:
         case PIO1_IRQ_0:
             return 0;
         case PIO0_IRQ_1:
         case PIO1_IRQ_1:
             return 1;
         default:
             return -1;
     }
 }
util_pio_get_irq_from_index()
uint util_pio_get_irq_from_index (PIO const pio, const uint idx)
Gets the NVIC PIO IRQ number using a PIO pointer and PIO IRQ index.
Parameters
idx
Returns
uint
Definition at line 250 of file util.c.
                     {
         check_pio_param(pio);
         assert(util_pio_irq_index_is_valid(idx));
         assert(util_pio_to_irq_map != NULL);
         const uint irq_num = util_pio_to_irq_map[
             pio_get_index(pio) + idx];
         check_irq_param(irq_num);
         return irq_num;
 }
References util_pio_irq_index_is_valid(), and util_pio_to_irq_map.
Referenced by hx711_multi__async_pio_irq_handler(), hx711_multi__init_irq(), hx711_multi__is_initd(), hx711_multi_async_start(), hx711_multi_close(), and util_irq_set_exclusive_pio_interrupt_num_handler().
util_pio_get_pio_from_irq()
PIO const util_pio_get_pio_from_irq (const uint irq_num)
Gets the PIO using the NVIC IRQ number.
Parameters
irq_num
Returns
PIO const
Definition at line 284 of file util.c.
{
     check_irq_param(irq_num);
     switch(irq_num) {
         case PIO0_IRQ_0:
         case PIO0_IRQ_1:
             return pio0;
         case PIO1_IRQ_0:
         case PIO1_IRQ_1:
             return pio1;
         default:
             return NULL;
     }
 }
util_pio_get_pis_from_pio_interrupt_num()
uint util_pio_get_pis_from_pio_interrupt_num (const uint pio_interrupt_num)
Definition at line 301 of file util.c.
{
         assert(util_routable_pio_interrupt_num_is_valid(
             pio_interrupt_num));
         const uint basePis = pis_interrupt0;
         const uint pis = basePis + pio_interrupt_num;
         assert(util_uint_in_range(
             pis, pis_interrupt0, pis_interrupt3));
         return pis;
 }
References util_routable_pio_interrupt_num_is_valid().
Referenced by hx711_multi__async_finish(), hx711_multi__async_pio_irq_handler(), hx711_multi__init_irq(), hx711_multi_close(), and util_irq_set_exclusive_pio_interrupt_num_handler().
util_pio_gpio_contiguous_init()
void util_pio_gpio_contiguous_init (PIO const pio, const uint base, const uint len)
Inits GPIO pins for PIO from base to base + len.
Parameters
pio
base
len
Definition at line 317 of file util.c.
                     {
         check_pio_param(pio);
         assert(len > 0);
         const uint l = base + len - 1;
         for(uint i = base; i <= l; ++i) {
             check_gpio_param(i);
             pio_gpio_init(pio, i);
         }
 }
Referenced by hx711_multi_pio_init().
util_pio_interrupt_num_is_valid()
bool util_pio_interrupt_num_is_valid (const uint pio_interrupt_num)
Check whether a PIO interrupt number is valid.
Parameters
pio_interrupt_num
Returns
true
false
Definition at line 374 of file util.c.
{
         return util_uint_in_range(
             pio_interrupt_num,
             UTIL_PIO_INTERRUPT_NUM_MIN,
             UTIL_PIO_INTERRUPT_NUM_MAX);
 }
References UTIL_PIO_INTERRUPT_NUM_MAX, and UTIL_PIO_INTERRUPT_NUM_MIN.
Referenced by hx711_multi_pio_init(), util_pio_interrupt_wait(), util_pio_interrupt_wait_clear(), util_pio_interrupt_wait_clear_timeout(), util_pio_interrupt_wait_cleared(), util_pio_interrupt_wait_cleared_timeout(), and util_pio_interrupt_wait_timeout().
util_pio_interrupt_wait()
void util_pio_interrupt_wait (PIO const pio, const uint pio_interrupt_num)
Waits for a given PIO interrupt to be set.
Parameters
pio
pio_interrupt_num
Definition at line 390 of file util.c.
{
         check_pio_param(pio);
         assert(util_pio_interrupt_num_is_valid(pio_interrupt_num));
         while(!pio_interrupt_get(pio, pio_interrupt_num)) {
             tight_loop_contents();
         }
 }
References util_pio_interrupt_num_is_valid().
Referenced by util_pio_interrupt_wait_clear().
util_pio_interrupt_wait_clear()
void util_pio_interrupt_wait_clear (PIO const pio, const uint pio_interrupt_num)
Waits for a given PIO interrupt to be set and then clears it.
Parameters
pio
pio_interrupt_num
Definition at line 430 of file util.c.
{
         check_pio_param(pio);
         assert(util_pio_interrupt_num_is_valid(pio_interrupt_num));
         util_pio_interrupt_wait(pio, pio_interrupt_num);
         pio_interrupt_clear(pio, pio_interrupt_num);
 }
References util_pio_interrupt_num_is_valid(), and util_pio_interrupt_wait().
util_pio_interrupt_wait_clear_timeout()
bool util_pio_interrupt_wait_clear_timeout (PIO const pio, const uint pio_interrupt_num, const absolute_time_t *const end)
Waits for a given PIO to be set within the timeout period and then clears it.
Parameters
pio
pio_interrupt_num
end
Returns
true if the interrupt was set within the timeout
false if the timeout was reached
Definition at line 459 of file util.c.
{
         check_pio_param(pio);
         assert(util_pio_interrupt_num_is_valid(pio_interrupt_num));
         assert(end != NULL);
         assert(!is_nil_time(*end));
         const bool ok = util_pio_interrupt_wait_timeout(
             pio,
             pio_interrupt_num,
             end);
         if(ok) {
             pio_interrupt_clear(
                 pio,
                 pio_interrupt_num);
         }
         return ok;
 }
References util_pio_interrupt_num_is_valid(), and util_pio_interrupt_wait_timeout().
util_pio_interrupt_wait_cleared()
void util_pio_interrupt_wait_cleared (PIO const pio, const uint pio_interrupt_num)
Waits until a given PIO interrupt is cleared.
Parameters
pio
pio_interrupt_num
Definition at line 400 of file util.c.
{
         check_pio_param(pio);
         assert(util_pio_interrupt_num_is_valid(pio_interrupt_num));
         while(pio_interrupt_get(pio, pio_interrupt_num)) {
             tight_loop_contents();
         }
 }
References util_pio_interrupt_num_is_valid().
util_pio_interrupt_wait_cleared_timeout()
bool util_pio_interrupt_wait_cleared_timeout (PIO const pio, const uint pio_interrupt_num, const absolute_time_t *const end)
Waits until the given interrupt is cleared, up to a maximum timeout.
Parameters
pio
pio_interrupt_num
end
Returns
true
false
Definition at line 410 of file util.c.
{
         check_pio_param(pio);
         assert(util_pio_interrupt_num_is_valid(pio_interrupt_num));
         assert(end != NULL);
         assert(!is_nil_time(*end));
         while(!time_reached(*end)) {
             if(!pio_interrupt_get(pio, pio_interrupt_num)) {
                 return true;
             }
         }
         return false;
 }
References util_pio_interrupt_num_is_valid().
util_pio_interrupt_wait_timeout()
bool util_pio_interrupt_wait_timeout (PIO const pio, const uint pio_interrupt_num, const absolute_time_t *const end)
Waits for a given PIO to be set within the timeout period.
Parameters
pio
pio_interrupt_num
end
Returns
true if the interrupt was set within the timeout
false if the timeout was reached
Definition at line 439 of file util.c.
{
         check_pio_param(pio);
         assert(util_pio_interrupt_num_is_valid(pio_interrupt_num));
         assert(end != NULL);
         assert(!is_nil_time(*end));
         while(!time_reached(*end)) {
             if(pio_interrupt_get(pio, pio_interrupt_num)) {
                 return true;
             }
         }
         return false;
 }
References util_pio_interrupt_num_is_valid().
Referenced by util_pio_interrupt_wait_clear_timeout().
util_pio_irq_index_is_valid()
bool util_pio_irq_index_is_valid (const uint idx)
Check whether PIO IRQ index is valid.
Parameters
idx
Returns
true
false
Definition at line 226 of file util.c.
{
     return util_uint_in_range(
         idx,
         UTIL_PIO_IRQ_INDEX_MIN,
         UTIL_PIO_IRQ_INDEX_MAX);
 }
References UTIL_PIO_IRQ_INDEX_MAX, and UTIL_PIO_IRQ_INDEX_MIN.
Referenced by hx711_multi__init_asert(), util_irq_set_exclusive_pio_interrupt_num_handler(), util_pio_get_irq_from_index(), and util_pion_get_irqn().
util_pio_sm_clear_isr()
void util_pio_sm_clear_isr (PIO const pio, const uint sm)
Clears a given state machine's ISR.
Parameters
pio
sm
Definition at line 355 of file util.c.
                    {
         check_pio_param(pio);
         check_sm_param(sm);
         const uint instr = pio_encode_pull(false, false);
         while(!pio_sm_is_tx_fifo_empty(pio, sm)) {
             pio_sm_exec(pio, sm, instr);
         }
 }
util_pio_sm_clear_osr()
void util_pio_sm_clear_osr (PIO const pio, const uint sm)
Clears a given state machine's OSR.
Parameters
pio
sm
Definition at line 344 of file util.c.
                    {
         check_pio_param(pio);
         check_sm_param(sm);
         const uint instr = pio_encode_push(false, false);
         while(!pio_sm_is_rx_fifo_empty(pio, sm)) {
             pio_sm_exec(pio, sm, instr);
         }
 }
util_pio_sm_clear_rx_fifo()
void util_pio_sm_clear_rx_fifo (PIO const pio, const uint sm)
Clears a given state machine's RX FIFO.
Parameters
pio
sm
Definition at line 334 of file util.c.
                    {
         check_pio_param(pio);
         check_sm_param(sm);
         while(!pio_sm_is_rx_fifo_empty(pio, sm)) {
             pio_sm_get(pio, sm);
         }
 }
Referenced by hx711_multi__async_start_dma().
util_pio_sm_is_enabled()
bool util_pio_sm_is_enabled (PIO const pio, const uint sm)
Check whether a given state machine is enabled.
Parameters
pio
sm
Returns
true
false
Definition at line 366 of file util.c.
                    {
         check_pio_param(pio);
         check_sm_param(sm);
         return (pio->ctrl & (1u << (PIO_CTRL_SM_ENABLE_LSB + sm))) != 0;
 }
Referenced by hx711__is_state_machine_enabled(), hx711__try_get_value(), and hx711_multi__is_state_machines_enabled().
util_pio_sm_try_get()
bool util_pio_sm_try_get (PIO const pio, const uint sm, uint32_t *const word, const uint threshold)
Attempts to get a word from the state machine's RX FIFO if more than threshold words are in the buffer.
Parameters
pio
sm
word variable to be set
threshold word count (1 word = 8 bytes)
Returns
true if word was set with the value from the RX FIFO
false if the number of words in the RX FIFO is below the threshold
Definition at line 484 of file util.c.
{
         check_pio_param(pio);
         check_sm_param(sm);
         assert(word != NULL);
         if(pio_sm_get_rx_fifo_level(pio, sm) >= threshold) {
             *word = pio_sm_get(pio, sm);
             return true;
         }
         return false;
 }
Referenced by hx711__try_get_value().
util_pion_get_irqn()
uint util_pion_get_irqn (PIO const pio, const uint irq_index)
Definition at line 233 of file util.c.
{
         check_pio_param(pio);
         assert(util_pio_irq_index_is_valid(irq_index));
         assert(util_pio_to_irq_map != NULL);
         const uint irq_num = util_pio_to_irq_map[
             pio_get_index(pio) + irq_index];
         check_irq_param(irq_num);
         return irq_num;
 }
References util_pio_irq_index_is_valid(), and util_pio_to_irq_map.
util_routable_pio_interrupt_num_is_valid()
bool util_routable_pio_interrupt_num_is_valid (const uint pio_interrupt_num)
Check whether a PIO interrupt number is a valid routable interrupt number.
Parameters
pio_interrupt_num
Returns
true
false
Definition at line 382 of file util.c.
{
         return util_uint_in_range(
             pio_interrupt_num,
             UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MIN,
             UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MAX);
 }
References UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MAX, and UTIL_ROUTABLE_PIO_INTERRUPT_NUM_MIN.
Referenced by hx711_multi_pio_init(), util_irq_set_exclusive_pio_interrupt_num_handler(), and util_pio_get_pis_from_pio_interrupt_num().
Variable Documentation
util_dma_to_irq_map
const uint8_t util_dma_to_irq_map[UTIL_NUM_DMA_IRQS] extern
Quick lookup for finding an NVIC IRQ number for a DMA interrupt index number.
Definition at line 55 of file util.c.
Referenced by util_dma_get_index_from_irq(), util_dma_get_irq_from_index(), and util_dma_get_irqn().
util_pio_to_irq_map
const uint8_t util_pio_to_irq_map[NUM_PIOS *2] extern
Quick lookup for finding an NVIC IRQ number for a PIO and interrupt index number.
Note
Each PIO has two interrupts, hence why this array is doubled.
Definition at line 48 of file util.c.
Referenced by util_pio_get_irq_from_index(), and util_pion_get_irqn().