// THIS FILE IS AUTOGENERATED BY GITHUB ACTIONS
// YOU SHOULD #include THIS FILE
// THE src/hx711_multi_reader.pio file IS NOT USABLE UNLESS
// YOU CONVERT IT USING pioasm
// SEE: /.github/workflows/generate_pio.yml

input.pio:44.8-25: syntax error, unexpected identifier, expecting "," or irq or pin or gpio
   44 | wait 1 DATA_READY_IRQ_NUM       ; wait for data ready from other state machine.
      |        ^~~~~~~~~~~~~~~~~~