// THIS FILE IS AUTOGENERATED BY GITHUB ACTIONS
// YOU SHOULD #include THIS FILE
// THE src/hx711_multi_awaiter.pio file IS NOT USABLE UNLESS
// YOU CONVERT IT USING pioasm
// SEE: /.github/workflows/generate_pio.yml

input.pio:36.14: syntax error, unexpected integer
   36 |     mov isr, 0                          ; clear the ISR; we don't care about the contents
      |              ^