// THIS FILE IS AUTOGENERATED BY GITHUB ACTIONS
// YOU SHOULD #include THIS FILE
// THE src/hx711_noblock_multi_waiter.pio file IS NOT USABLE UNLESS
// YOU CONVERT IT USING pioasm
// SEE: /.github/workflows/generate_pio.yml

input.pio:73.19: the maximum side set value is 0 based on the configuration specified at 1.1
   73 | pull noblock side 1
      |                   ^