name: cppcheck-action

on: [push, workflow_dispatch]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          enable: all
          inline_suppression: enable
          force_language: c
          other_options: --suppress=unusedFunction --suppress=missingInclude
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: publish report
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
